### PR TITLE
Add SetPlayerClassVar 🙂

### PR DESCRIPTION
**Pull request by dr3murr**
This is a very good commit for the game system and it adds many useful features for the game system that scripters have requested me to add and I think it is a good commit that should be merged 🙂🙂 🙂 🙂🙂🙂🙂🙂 usage:
```
script_client GetLocalClientPlayer().SetPlayerClassVar("jumpheight", "10") // this only sets client-side, useful for prediction 

script GetPlayerArray()[0].SetPlayerClassVar("jumpheight", "56000") // sets on client AND server WOOOOO
```
image

### CODE REVIEW

**Comment by ttvmkos** [comment]
W COMITT

entity method registration + set player settings from server scripts!!

**Comment by dr3murr** [comment]
Screenshot_20240827-021055965 (1)

**Comment by dr3murr** [comment]
things to do before merge:
- make code not suck
- add validation of key and value
- make sure player is local player when run in client vm

**Comment by dr3murr** [comment]
Fixed security 🙂
image

**Comment by Mauler125** [comment]
Thanks for the PR, I've made PR #129 which features your class function registration logic. I however did make the change of moving the class var setter over a dedicated net message as this is more secure than doing it over Cbuf, and drops the requirement of checking on each key string.

The new net message is: "svc_SetClassVar".
Player function: player.SetClassVar("key", "value").
Global function: SetClassVarSynced("key", "value").

**Pull request closed without merging**
